DROP TABLE IF EXISTS orders CASCADE;

CREATE TABLE orders (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  order_placed_status BOOLEAN DEFAULT FALSE,
  food_ready_status BOOLEAN DEFAULT FALSE
);
